name: Publish to NuGet

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}
      
    - name: Install dependencies
      run: dotnet restore **/*.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore **/*.sln

    - name: Generate NuGet package
      run: |  
        cd NStack/NStack
        dotnet pack --configuration Release --output out --no-build  

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./NStack/NStack/out/*.nupkg --skip-duplicate --no-symbols true
